application: gae-php
version: 1
runtime: php55
api_version: 1

handlers:
- url: /.*
  script: index.php

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

