application: tayutaedomo-php
version: 1
runtime: php55
api_version: 1

handlers:
- url: /phpinfo.php
  script: app/phpinfo.php

- url: /
  script: app/index.php

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

